### ISSUE TITLE
Create client to local mist

### ISSUE THREAD

**Issue by lexxito** [mistio/mist.client#24]
Good day! 

currently, I am working on the evaluation of existing CMPs for my master project and Mistio is one them.

I faced a problem to use python client for local mistio docker.

client = MistClient(mist_uri='http://localhost/', email="example@zhaw.ch", password="changeme")

return error: 
raise Exception(resp.content)

Exception: <!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes">
  <base href="/landing//build/48134f5709b63f4f91400f5e440d57d656698a64/bundled/"></base>

  <title>Mist.io :: hybrid cloud management platform</title>
  <meta name="description" content="A secure cloud management platform for automation, orchestration, cost and usage monitoring of public and private clouds. Provides multi-cloud RBAC. Enables self service provisioning. Cost analysis and cloud spending optimization">

  
  <link rel="shortcut icon" sizes="32x32" href="images/mist-icon-32.png">

  <meta name="theme-color" content="#fff">
  <link rel="manifest" href="manifest.json">

  
  
  

  <script> var CSRF_TOKEN="79d6d0e8ae1763f8d0c0a03ba597adb2e9fbd58ea9aa4d6c72b9a9be6adecc84"</script>
  <script> var CATEGORIES=[{'items': {'fold': {'subcopy': 'Mist.io is a single dashboard to manage multi-cloud infrastructure', 'copy': '', 'image': 'images/mockup-imac-n4.png', 'cta': 'Get Started', 'alt': 'Mist.io cloud management dashboard'}}, 'href': '/', 'name': 'home', 'template': 'home', 'title': 'Home'}]</script>
  <script> var True = true, False = false, CONFIG = {'features': {'ab': False, 'monitoring': True, 'billing': False, 'r12ns': False, 'docs': 'https://docs.mist.io/', 'support': 'https://docs.mist.io/contact', 'signin_email': True, 'rbac': False, 'signin_github': False, 'signup_github': False, 'landing_footer': False, 'signin_google': False, 'orchestration': False, 'signup_google': False, 'signin_home': False, 'signup_email': True, 'tunnels': False, 'insights': False}, 'email': {'info': 'info@mist.io', 'support': 'support@mist.io', 'sales': 'sales@mist.io'}, 'portalName': 'Mist.io', 'stripeKey': ''}</script>
  <script src="/landing/bower_components/webcomponentsjs/webcomponents-lite.js"></script>

  <script>
   window.twttr = (function(d, s, id) {
              var js, fjs = d.getElementsByTagName(s)[0],
                t = window.twttr || {};
              if (d.getElementById(id)) return t;
              js = d.createElement(s);
              js.id = id;
              js.src = "https://platform.twitter.com/widgets.js";
              fjs.parentNode.insertBefore(js, fjs);

              t._e = [];
              t.ready = function(f) {
                t._e.push(f);
              };

              return t;
            }(document, "script", "twitter-wjs"));
    // setup Polymer options
    window.Polymer = {lazyRegister: true};

    var ANIMATIONS = false;
    // Disable animations in Polyfilled browsers for now
    if ('registerElement' in document
          && 'import' in document.createElement('link')
          && 'content' in document.createElement('template'))
          ANIMATIONS = true;
  </script>
  
  
  
  

  <style>
    body {
      margin: 0;
      padding: 0;
      min-height: 100vh;
      box-sizing: border-box;
    }

    
    @font-face {
      font-family: "Roboto";
      src: local(Roboto Thin), url("fonts/roboto/Roboto-Thin.eot");
      src: url("fonts/roboto/Roboto-Thin.eot?#iefix") format("embedded-opentype"), url("fonts/roboto/Roboto-Thin.woff2") format("woff2"), url("fonts/roboto/Roboto-Thin.woff") format("woff"), url("fonts/roboto/Roboto-Thin.ttf") format("truetype");
      font-weight: 200;
    }

    @font-face {
      font-family: "Roboto";
      src: local(Roboto Light), url("fonts/roboto/Roboto-Light.eot");
      src: url("fonts/roboto/Roboto-Light.eot?#iefix") format("embedded-opentype"), url("fonts/roboto/Roboto-Light.woff2") format("woff2"), url("fonts/roboto/Roboto-Light.woff") format("woff"), url("fonts/roboto/Roboto-Light.ttf") format("truetype");
      font-weight: 300;
    }

    @font-face {
      font-family: "Roboto";
      src: local(Roboto Regular), url("fonts/roboto/Roboto-Regular.eot");
      src: url("fonts/roboto/Roboto-Regular.eot?#iefix") format("embedded-opentype"), url("fonts/roboto/Roboto-Regular.woff2") format("woff2"), url("fonts/roboto/Roboto-Regular.woff") format("woff"), url("fonts/roboto/Roboto-Regular.ttf") format("truetype");
      font-weight: 400;
    }

    @font-face {
      font-family: "Roboto";
      src: url("fonts/roboto/Roboto-Medium.eot");
      src: url("fonts/roboto/Roboto-Medium.eot?#iefix") format("embedded-opentype"), url("fonts/roboto/Roboto-Medium.woff2") format("woff2"), url("fonts/roboto/Roboto-Medium.woff") format("woff"), url("fonts/roboto/Roboto-Medium.ttf") format("truetype");
      font-weight: 500;
    }

    @font-face {
      font-family: "Roboto";
      src: url("fonts/roboto/Roboto-Bold.eot");
      src: url("fonts/roboto/Roboto-Bold.eot?#iefix") format("embedded-opentype"), url("fonts/roboto/Roboto-Bold.woff2") format("woff2"), url("fonts/roboto/Roboto-Bold.woff") format("woff"), url("fonts/roboto/Roboto-Bold.ttf") format("truetype");
      font-weight: 700;
    }

    @media only screen and (max-width: 993px) {
        body {
            font-size: 16px;
        }
    }
    html {
      font-size: 14px;
      line-height: 1.5;
      font-family: "Roboto", sans-serif;
      font-weight: normal;
      color: rgba(0, 0, 0, 0.87);
    }

    @media only screen and (min-width: 0) {
      html {
        font-size: 14px;
      }
    }

    @media only screen and (min-width: 992px) {
      html {
        font-size: 14.5px;
      }
    }

    @media only screen and (min-width: 1200px) {
      html {
        font-size: 15px;
      }
    }

    body {
      position: relative;
      font-size: 18px;
      color: #444;
      display: flex;
      min-height: 100vh;
      flex-direction: column;
    }

    /* styling for render while resources are loading */
    landing-app[unresolved] {
      display: block;
      min-height: 101vh;
      line-height: 68px;
      text-align: center;
      font-size: 18px;
      font-weight: 600;
      letter-spacing: 0.3em;
      color: #202020;
      padding: 0 16px;
      overflow: visible;
    }

    div.wave {
      border-radius: 50%;
      background: black;
      width: 4000px;
      height: 4000px;
      position: fixed;
      -webkit-user-select: none;
      user-select: none;
      overflow: hidden;
      z-index: 10;
    }
  </style>

</head>
<body>

  <landing-app unresolved>
  </landing-app>

  <script>
    window.performance && performance.mark && performance.mark('index.html');
    if (CONFIG) document.querySelector('landing-app').config = CONFIG;
  </script>
  <link rel="import" href="src/landing-app.html">

  
  
  

  
  
  
  <noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=1647503578815528&ev=PageView&noscript=1"
  /></noscript>
  

  
  
  <noscript><a href="https://www.olark.com/site/5179-329-10-7357/contact" title="Contact us" target="_blank">Questions? Feedback?</a> powered by <a href="http://www.olark.com?welcome" title="Olark live chat software">Olark live chat software</a></noscript>
  

</body>
</html>

**Comment by d-mo** [comment]
Thank you for this report. The Mist client is overdue for an update. We're currently working on bringing it up to speed. We'll release a new version next week that fixes the above issue along with some others. I'll update this ticket once the new release is ready.
